SELECT
@idpdam,
@id:=@id+1 AS idrekeningair,
pl.id AS idpelangganair,
pr.idperiode AS idperiode,
g.`idgolongan` AS idgolongan,
COALESCE(d.`iddiameter`,-1) AS iddiameter,
-1 AS idjenispipa,
-1 AS idkwh,
r.`idrayon` AS idrayon,
k.`idkelurahan` AS idkelurahan,
ko.`idkolektif` AS idkolektif,
-1 AS idadministrasilain,
-1 AS idpemeliharaanlain,
-1 AS idretribusilain,
1 AS idstatus,
p.flag AS idflag,
p.stanlalu AS stanlalu,
IFNULL(p.stanskrg, 0) AS stanskrg,
IFNULL(p.stanangkat, 0) AS stanangkat,
IFNULL(p.pakai, 0) AS pakai,
0 AS pakaikalkulasi,
IFNULL(p.biayapemakaian, 0) AS biayapemakaian,
IFNULL(p.administrasi, 0) AS administrasi,
IFNULL(p.pemeliharaan, 0) AS pemeliharaan,
IFNULL(p.retribusi, 0) AS retribusi,
IFNULL(p.pelayanan, 0) AS pelayanan,
IFNULL(p.airlimbah, 0) AS airlimbah,
IFNULL(p.dendapakai0, 0) AS dendapakai0,
IFNULL(p.administrasilain, 0) AS administrasilain,
IFNULL(p.pemeliharaanlain, 0) AS pemeliharaanlain,
IFNULL(p.retribusilain, 0) AS retribusilain,
IFNULL(p.ppn, 0) AS ppn,
IFNULL(p.meterai, 0) AS meterai,
IFNULL(p.rekair, 0) AS rekair,
IFNULL(p.dendatunggakan, 0) AS denda,
0 AS diskon,
0 AS deposit,
IFNULL(p.total, 0) AS total,
0 AS hapussecaraakuntansi,
NULL AS waktuhapussecaraakuntansi,
NULL AS iddetailcyclepembacaan,
NULL AS tglpenentuanbaca,
1 AS flagbaca,
0 AS metodebaca,
DATE(NOW()) AS waktubaca,
DATE_FORMAT(NOW(), '%H:%i:%s') AS jambaca,
pb.`kodepetugasbaca` AS petugasbaca,
kl.idkelainan AS kelainan,
0 AS stanbaca,
DATE(NOW()) AS waktukirimhasilbaca,
DATE_FORMAT(NOW(), '%H:%i:%s') AS jamkirimhasilbaca,
NULL AS memolapangan,
NULL AS lampiran,
0 AS taksasi,
0 AS taksir,
0 AS flagrequestbacaulang,
NULL AS waktuupdaterequestbacaulang,
1 AS flagkoreksi,
DATE(NOW()) AS waktukoreksi,
DATE_FORMAT(NOW(), '%H:%i:%s') AS jamkoreksi,
1 AS flagverifikasi,
DATE(NOW()) AS waktuverifikasi,
DATE_FORMAT(NOW(), '%H:%i:%s') AS jamverifikasi,
NULL AS userverifikasi,
1 AS flagpublish,
DATE(NOW()) AS waktupublish,
DATE_FORMAT(NOW(), '%H:%i:%s') AS jampublish,
NULL AS userpublish,
NULL AS latitude,
NULL AS longitude,
NULL AS latitudebulanlalu,
NULL AS longitudebulanlalu,
1 AS adafotometer,
0 AS adafotorumah,
0 AS adavideo,
0 AS flagminimumpakai,
0 AS pakaibulanlalu,
0 AS pakai2bulanlalu,
0 AS pakai3bulanlalu,
0 AS pakai4bulanlalu,
0 AS persentasebulanlalu,
0 AS persentase2bulanlalu,
0 AS persentase3bulanlalu,
NULL AS kelainanbulanlalu,
NULL AS kelainan2bulanlalu,
p.flagangsur AS flagangsur,
NULL AS idangsuran,
NULL AS idmodule,
0 AS flagkoreksibilling,
p.tglmulaidenda AS tglmulaidenda1,
p.tglmulaidenda2 AS tglmulaidenda2,
p.tglmulaidenda3 AS tglmulaidenda3,
p.tglmulaidenda4 AS tglmulaidenda4,
p.tglmulaidendaperbulan AS tglmulaidendaperbulan,
NULL AS tglmulaidendaperhari,
0 AS flaghasbeenpublish,
0 AS flagdrdsusulan,
NULL AS waktudrdsusulan,
NOW() AS waktuupdate,
0 AS flaghapus
FROM piutang p
JOIN pelanggan pl ON pl.nosamb=p.nosamb
JOIN `kotaparepare_dataawal`.`master_periode` pr ON pr.`kodeperiode`=p.periode AND pr.`idpdam`=@idpdam
LEFT JOIN `kotaparepare_dataawal`.`master_tarif_golongan` g ON g.`kodegolongan`=p.kodegol AND g.`idpdam`=@idpdam
LEFT JOIN `kotaparepare_dataawal`.`master_tarif_diameter` d ON d.kodediameter=p.kodediameter AND d.`idpdam`=@idpdam
LEFT JOIN `kotaparepare_dataawal`.`master_attribute_rayon` r ON r.koderayon=p.koderayon AND r.`idpdam`=@idpdam
LEFT JOIN `kotaparepare_dataawal`.`master_attribute_kelurahan` k ON k.kodekelurahan=pl.kodekelurahan AND k.`idpdam`=@idpdam
LEFT JOIN `kotaparepare_dataawal`.`master_attribute_kolektif` ko ON ko.kodekolektif=p.kodekolektif AND ko.`idpdam`=@idpdam
LEFT JOIN `kotaparepare_dataawal`.`master_attribute_petugas_baca` pb ON pb.`petugasbaca`=TRIM(SUBSTRING_INDEX(p.pembacameter, '(', 1)) AND pb.`idpdam`=@idpdam
LEFT JOIN `kotaparepare_dataawal`.`master_attribute_kelainan` kl ON kl.`kelainan`=p.kelainan
,(SELECT @id:=@lastid) AS id
WHERE p.periode BETWEEN 202502 AND 202504