SELECT
 @idpdam,
 id AS idgolongan,
 administrasi,
 pemeliharaan,
 pelayanan,
 retribusi,
 retribusi_pakai AS retribusipakai,
 airlimbah,
 minpakai,
 dendapakai0,
 ppn,
 bb1,
 ba1,
 bb2,
 ba2,
 bb3,
 ba3,
 bb4,
 ba4,
 bb5,
 ba5,
 t1,
 t2,
 t3,
 t4,
 t5,
 mindenda,
 t1_tetap AS t1tetap,
 t2_tetap AS t2tetap,
 t3_tetap AS t3tetap,
 t4_tetap AS t4tetap,
 t5_tetap AS t5tetap,
 dendatunggakan AS dendatunggakan1,
 dendatunggakan2,
 dendatunggakan3,
 dendatunggakan4,
 dendatunggakanperbulan,
 trf_denda_berdasarkan_persen AS trfdendaberdasarkanpersen,
 0 AS biayaadminberlakupada,
 0 AS dendatunggakanperhari,
 0 AS maxtotaldendaperhari,
 NOW() AS waktuupdate
FROM
 golongan
 WHERE aktif=1