SELECT
@idpdam AS idpdam,
@id:=@id+1 AS idrekeningair,
pel.idsamb AS idpelangganair,
per.id AS idperiode,
COALESCE(gol.id,-1) AS idgolongan,
COALESCE(dia.id,-1) AS iddiameter,
1 AS idjenispipa,
1 AS idkwh,
ray.id AS idrayon,
kel.id AS idkelurahan,
-1 AS idkolektif,
-1 AS idadministrasilain,
-1 AS idpemeliharaanlain,
ret.id AS idretribusilain,
1 AS idstatus,
1 AS idflag,
IFNULL(rek.stanawal, 0)  AS stanlalu,
IFNULL(rek.stanakhir, 0) AS stanskrg,
0 AS stanangkat,
IFNULL(rek.pakai, 0) AS pakai,
0 AS pakaikalkulasi,
IFNULL(rek.biaya1, 0)+IFNULL(rek.biaya2, 0)+IFNULL(rek.biaya3, 0)+IFNULL(rek.biaya4, 0) AS biayapemakaian,
IFNULL(rek.adm, 0) AS administrasi,
IFNULL(rek.dwm, 0) AS pemeliharaan,
IFNULL(rek.retribusi, 0) AS retribusi,
0 AS pelayanan,
0 AS airlimbah,
0 AS dendapakai0,
0 AS administrasilain,
0 AS pemeliharaanlain,
0 AS retribusilain,
0 AS ppn,
IFNULL(rek.meterai, 0) AS meterai,
IFNULL(rek.biaya1, 0)+IFNULL(rek.biaya2, 0)+IFNULL(rek.biaya3, 0)+IFNULL(rek.biaya4, 0)+IFNULL(rek.adm, 0)+IFNULL(rek.dwm, 0)+IFNULL(rek.retribusi, 0)+IFNULL(rek.meterai, 0) AS rekair,
IFNULL(rek.denda, 0) AS denda,
0 AS diskon,
0 AS deposit,
IFNULL(rek.total, 0) AS total,
0 AS hapussecaraakuntansi,
NULL AS waktuhapussecaraakuntansi,
NULL AS iddetailcyclepembacaan,
NULL AS tglpenentuanbaca,
1 AS flagbaca,
NULL AS metodebaca,
DATE(rek.tglcatat)AS waktubaca,
TIME(rek.tglcatat) AS jambaca,
pbc.kodepetugas AS petugasbaca,
NULL AS kelainan,
0 AS stanbaca,
DATE(rek.tglcatat) AS waktukirimhasilbaca,
TIME(rek.tglcatat) AS jamkirimhasilbaca,
'' AS memolapangan,
'' AS lampiran,
0 AS taksasi,
0 AS taksir,
0 AS flagrequestbacaulang,
NULL AS waktuupdaterequestbacaulang,
1 AS flagkoreksi,
DATE(rek.tglcatat) AS waktukoreksi,
TIME(rek.tglcatat) AS jamkoreksi,
1 AS flagverifikasi,
DATE(rek.tglcatat) AS waktuverifikasi,
TIME(rek.tglcatat) AS jamverifikasi,
NULL AS userverifikasi,
1 AS flagpublish,
DATE(rek.tglcatat) AS waktupublish,
TIME(rek.tglcatat) AS jampublish,
NULL AS userpublish,
rek.lat AS latitude,
rek.lng AS longitude,
rek.lat AS latitudebulanlalu,
rek.lng AS longitudebulanlalu,
1 AS adafotometer,
0 AS adafotorumah,
0 AS adavideo,
0 AS flagminimumpakai,
0 AS pakaibulanlalu,
0 AS pakai2bulanlalu,
0 AS pakai3bulanlalu,
0 AS pakai4bulanlalu,
0 AS persentasebulanlalu,
0 AS persentase2bulanlalu,
0 AS persentase3bulanlalu,
NULL AS kelainanbulanlalu,
NULL AS kelainan2bulanlalu,
0 AS flagangsur,
NULL AS idangsuran,
NULL AS idmodule,
0 AS flagkoreksibilling,
per.tglmulaidenda AS tglmulaidenda1,
per.tglmulaidenda2 AS tglmulaidenda2,
per.tglmulaidenda3 AS tglmulaidenda3,
per.tglmulaidenda4 AS tglmulaidenda4,
per.tglmulaidendaperbulan AS tglmulaidendaperbulan,
NULL AS tglmulaidendaperhari,
1 AS flaghasbeenpublish,
0 AS flagdrdsusulan,
NULL AS waktudrdsusulan,
NOW() AS waktuupdate,
0 AS flaghapus
FROM [bacameter].`tbl_rekair` rek
JOIN [bacameter].`tbl_samb` pel ON pel.nosamb = rek.nosamb
JOIN periode_map per ON per.periode = CONCAT(rek.tahun, LPAD(rek.bulan,2,'0'))
LEFT JOIN golongan_map gol ON gol.kodegol = rek.gol AND gol.aktif = 1
LEFT JOIN `pelanggan_dia_map` dia1 ON rek.nosamb=dia1.nosamb
LEFT JOIN diameter_map dia ON dia.kodediameter = dia1.kodediameter AND dia.aktif = 1
LEFT JOIN rayon_map ray ON ray.koderayon = pel.kdipa
LEFT JOIN kelurahan_map kel ON kel.kelurahan = pel.kel
-- LEFT JOIN kolektif_map kol ON kol.kodekolektif = rek.kodekolektif
-- LEFT JOIN byadministrasi_lain_map adm ON adm.kode = rek.kodeadministrasilain
-- LEFT JOIN bypemeliharaan_lain_map pem ON pem.kode = rek.kodepemeliharaanlain
LEFT JOIN `pelanggan_ret_map` ret1 ON ret1.nosamb = rek.nosamb
LEFT JOIN byretribusi_lain_map ret ON ret.kode = ret1.koderetribusilain
-- LEFT JOIN [bacameter].hasilbaca0825 hsl ON hsl.idpelanggan=rek.nosamb
LEFT JOIN [bsbs].petugasbaca_map pbc ON pbc.nama = rek.pencatat
-- LEFT JOIN kelainan_map kln ON kln.kelainan = rek.kelainan
,(SELECT @id := 0) AS id
WHERE rek.tahun='2025' AND rek.bulan='7';