SELECT
@idpdam,
@id:=@id+1 AS idrekeningair,
pl.id AS idpelangganair,
pr.idperiode AS idperiode,
g.`idgolongan` AS idgolongan,
COALESCE(d.`iddiameter`,-1) AS iddiameter,
-1 AS idjenispipa,
-1 AS idkwh,
r.`idrayon` AS idrayon,
k.`idkelurahan` AS idkelurahan,
ko.`idkolektif` AS idkolektif,
-1 AS idadministrasilain,
-1 AS idpemeliharaanlain,
-1 AS idretribusilain,
1 AS idstatus,
p.flag AS idflag,
p.stanlalu AS stanlalu,
IFNULL(p.stanskrg, 0) AS stanskrg,
IFNULL(p.stanangkat, 0) AS stanangkat,
IFNULL(p.pakai, 0) AS pakai,
0 AS pakaikalkulasi,
IFNULL(p.biayapemakaian, 0) AS biayapemakaian,
IFNULL(p.administrasi, 0) AS administrasi,
IFNULL(p.pemeliharaan, 0) AS pemeliharaan,
IFNULL(p.retribusi, 0) AS retribusi,
IFNULL(p.pelayanan, 0) AS pelayanan,
IFNULL(p.airlimbah, 0) AS airlimbah,
IFNULL(p.dendapakai0, 0) AS dendapakai0,
IFNULL(p.administrasilain, 0) AS administrasilain,
IFNULL(p.pemeliharaanlain, 0) AS pemeliharaanlain,
IFNULL(p.retribusilain, 0) AS retribusilain,
IFNULL(p.ppn, 0) AS ppn,
IFNULL(p.meterai, 0) AS meterai,
IFNULL(p.rekair, 0) AS rekair,
IFNULL(p.dendatunggakan, 0) AS denda,
0 AS diskon,
0 AS deposit,
IFNULL(p.total, 0) AS total,
0 AS hapussecaraakuntansi,
NULL AS waktuhapussecaraakuntansi,
NULL AS iddetailcyclepembacaan,
NULL AS tglpenentuanbaca,
1 AS flagbaca,
IF(h.terbaca=1,4,0) AS metodebaca,
DATE(h.waktubaca) AS waktubaca,
DATE_FORMAT(h.waktubaca, '%H:%i:%s') AS jambaca,
h.kodepetugas AS petugasbaca,
kl.idkelainan AS kelainan,
h.datalapangan AS stanbaca,
DATE(h.waktuupload) AS waktukirimhasilbaca,
DATE_FORMAT(h.waktuupload, '%H:%i:%s') AS jamkirimhasilbaca,
NULL AS memolapangan,
NULL AS lampiran,
0 AS taksasi,
0 AS taksir,
0 AS flagrequestbacaulang,
NULL AS waktuupdaterequestbacaulang,
1 AS flagkoreksi,
DATE(h.waktuupload) AS waktukoreksi,
DATE_FORMAT(h.waktuupload, '%H:%i:%s') AS jamkoreksi,
1 AS flagverifikasi,
DATE(h.waktuverifikasi) AS waktuverifikasi,
DATE_FORMAT(h.waktuverifikasi, '%H:%i:%s') AS jamverifikasi,
us.iduser AS userverifikasi,
1 AS flagpublish,
DATE(h.waktuverifikasi) AS waktupublish,
DATE_FORMAT(h.waktuverifikasi, '%H:%i:%s') AS jampublish,
NULL AS userpublish,
h.latitude AS latitude,
h.longitude AS longitude,
NULL AS latitudebulanlalu,
NULL AS longitudebulanlalu,
1 AS adafotometer,
h.adafotorumah AS adafotorumah,
h.adavideo AS adavideo,
0 AS flagminimumpakai,
COALESCE(h.pakai1,0) AS pakaibulanlalu,
COALESCE(h.pakai2,0) AS pakai2bulanlalu,
COALESCE(h.pakai3,0) AS pakai3bulanlalu,
0 AS pakai4bulanlalu,
CAST(REPLACE(IF(h.persen1='-',0,COALESCE(h.persen1,0)),',','.') AS DECIMAL(10,2)) AS persentasebulanlalu,
CAST(REPLACE(IF(h.persen2='-',0,COALESCE(h.persen2,0)),',','.') AS DECIMAL(10,2)) AS persentase2bulanlalu,
CAST(REPLACE(IF(h.persen3='-',0,COALESCE(h.persen3,0)),',','.') AS DECIMAL(10,2)) AS persentase3bulanlalu,
NULL AS kelainanbulanlalu,
NULL AS kelainan2bulanlalu,
p.flagangsur AS flagangsur,
NULL AS idangsuran,
NULL AS idmodule,
0 AS flagkoreksibilling,
p.tglmulaidenda AS tglmulaidenda1,
p.tglmulaidenda2 AS tglmulaidenda2,
p.tglmulaidenda3 AS tglmulaidenda3,
p.tglmulaidenda4 AS tglmulaidenda4,
p.tglmulaidendaperbulan AS tglmulaidendaperbulan,
NULL AS tglmulaidendaperhari,
0 AS flaghasbeenpublish,
0 AS flagdrdsusulan,
NULL AS waktudrdsusulan,
NOW() AS waktuupdate,
0 AS flaghapus
FROM bayar p
JOIN pelanggan pl ON pl.nosamb=p.nosamb
JOIN [dataawal].`master_periode` pr ON pr.`kodeperiode`=p.periode AND pr.`idpdam`=@idpdam
LEFT JOIN [dataawal].`master_tarif_golongan` g ON g.`kodegolongan`=p.kodegol AND g.`idpdam`=@idpdam
LEFT JOIN [dataawal].`master_tarif_diameter` d ON d.kodediameter=p.kodediameter AND d.`idpdam`=@idpdam
LEFT JOIN [dataawal].`master_attribute_rayon` r ON r.koderayon=p.koderayon AND r.`idpdam`=@idpdam
LEFT JOIN [dataawal].`master_attribute_kelurahan` k ON k.kodekelurahan=pl.kodekelurahan AND k.`idpdam`=@idpdam
LEFT JOIN [dataawal].`master_attribute_kolektif` ko ON ko.kodekolektif=p.kodekolektif AND ko.`idpdam`=@idpdam
LEFT JOIN [bacameter].tampung_hasilbaca h on h.kode=p.kode
LEFT JOIN [dataawal].`master_attribute_kelainan` kl ON kl.`kodekelainan`=h.kodekelainan AND kl.`idpdam`=@idpdam
LEFT JOIN [bacameter].`userakses` u ON u.iduser=h.iduserupdate
LEFT JOIN [dataawal].`master_user` us ON us.nama=u.nama AND us.namauser=u.namauser AND us.idpdam=@idpdam
,(SELECT @id:=@lastid) AS id
WHERE p.periode BETWEEN 202502 AND 202504