SELECT
@idpdam AS idpdam,
@id:=@id+1 AS idgolongan,
administrasi AS administrasi,
pemeliharaan AS pemeliharaan,
pelayanan AS pelayanan,
retribusi AS retribusi,
retribusi_pakai AS retribusipakai,
airlimbah AS airlimbah,
minpakai AS minpakai,
dendapakai0 AS dendapakai0,
ppn AS ppn,
bb1 AS bb1,
ba1 AS ba1,
bb2 AS bb2,
ba2 AS ba2,
bb3 AS bb3,
ba3 AS ba3,
bb4 AS bb4,
ba4 AS ba4,
bb5 AS bb5,
ba5 AS ba5,
t1 AS t1,
t2 AS t2,
t3 AS t3,
t4 AS t4,
t5 AS t5,
mindenda AS mindenda,
t1_tetap AS t1tetap,
t2_tetap AS t2tetap,
t3_tetap AS t3tetap,
t4_tetap AS t4tetap,
t5_tetap AS t5tetap,
dendatunggakan AS dendatunggakan1,
dendatunggakan2 AS dendatunggakan2,
dendatunggakan3 AS dendatunggakan3,
dendatunggakan4 AS dendatunggakan4,
dendatunggakanperbulan AS dendatunggakanperbulan,
trf_denda_berdasarkan_persen AS trfdendaberdasarkanpersen,
0 AS biayaadminberlakupada,
0 AS dendatunggakanperhari,
0 AS maxtotaldendaperhari,
NOW() AS waktuupdate
FROM
golongan,
(SELECT @id:=0) AS id;