SELECT
 idlistdata,
 ENDPOINT,
 fieldkey,
 fielddisplayvalue1,
 fielddisplayname1,
 fielddisplayvalue2,
 fielddisplayname2,
 dbsetname,
 flaghapus,
 waktuupdate
FROM
 master_attribute_tipe_permohonan_config_list_data