-- permohonan_pelanggan_air_koreksi_rekening
-- new(0, "id")
-- new(1, "idpdam")
-- new(2, "idpelangganair")
-- new(3, "idperiode")
-- new(4, "idpermohonan")
-- new(5, "waktuusulan")
-- new(6, "statusverifikasilapangan")
-- new(7, "waktustatusverifikasilapangan")
-- new(8, "keteranganstatusverifikasilapangan")
-- new(9, "statusverifikasipusat")
-- new(10, "waktustatusverifikasipusat")
-- new(11, "keteranganstatusverifikasipusat")
-- new(12, "nomorba")
-- new(13, "stanlalu")
-- new(14, "stanskrg")
-- new(15, "stanangkat")
-- new(16, "pakai")
-- new(17, "biayapemakaian")
-- new(18, "administrasi")
-- new(19, "pemeliharaan")
-- new(20, "retribusi")
-- new(21, "pelayanan")
-- new(22, "airlimbah")
-- new(23, "dendapakai0")
-- new(24, "administrasilain")
-- new(25, "pemeliharaanlain")
-- new(26, "retribusilain")
-- new(27, "ppn")
-- new(28, "meterai")
-- new(29, "rekair")
-- new(30, "denda")
-- new(31, "total")
-- new(32, "flaghanyaabonemen")
-- new(33, "stanlalu_usulan")
-- new(34, "stanskrg_usulan")
-- new(35, "stanangkat_usulan")
-- new(36, "pakai_usulan")
-- new(37, "biayapemakaian_usulan")
-- new(38, "administrasi_usulan")
-- new(39, "pemeliharaan_usulan")
-- new(40, "retribusi_usulan")
-- new(41, "pelayanan_usulan")
-- new(42, "airlimbah_usulan")
-- new(43, "dendapakai0_usulan")
-- new(44, "administrasilain_usulan")
-- new(45, "pemeliharaanlain_usulan")
-- new(46, "retribusilain_usulan")
-- new(47, "meterai_usulan")
-- new(48, "ppn_usulan")
-- new(49, "rekair_usulan")
-- new(50, "denda_usulan")
-- new(51, "total_usulan")
-- new(52, "stanlalu_baru")
-- new(53, "stanskrg_baru")
-- new(54, "stanangkat_baru")
-- new(55, "pakai_baru")
-- new(56, "biayapemakaian_baru")
-- new(57, "administrasi_baru")
-- new(58, "pemeliharaan_baru")
-- new(59, "retribusi_baru")
-- new(50, "pelayanan_baru")
-- new(51, "airlimbah_baru")
-- new(52, "dendapakai0_baru")
-- new(53, "administrasilain_baru")
-- new(54, "pemeliharaanlain_baru")
-- new(55, "retribusilain_baru")
-- new(56, "meterai_baru")
-- new(57, "ppn_baru")
-- new(58, "rekair_baru")
-- new(59, "denda_baru")
-- new(60, "total_baru")
-- new(61, "statuspermohonan")
-- new(62, "flaghapus")
-- new(63, "waktuupdate")

SET @idtipepermohonan=(SELECT idtipepermohonan FROM `kotaparepare_dataawal`.`master_attribute_tipe_permohonan` WHERE idpdam=@idpdam AND `kodetipepermohonan`='KREKAIR');

SELECT
@id:=@id+1 AS `id`,
@idpdam AS `idpdam`,
pl.`idpelangganair` AS `idpelangganair`,
pr.`idperiode` AS `idperiode`,
pp.`idpermohonan` AS `idpermohonan`,
p.`tanggalba` AS `waktuusulan`,
1 AS `statusverifikasilapangan`,
p.`tanggalba` AS `waktustatusverifikasilapangan`,
NULL AS `keteranganstatusverifikasilapangan`,
1 AS `statusverifikasipusat`,
p.`tanggalba` AS `waktustatusverifikasipusat`,
NULL AS `keteranganstatusverifikasipusat`,
p.`nomorba` AS `nomorba`,
d.`stanlalu_lama` AS `stanlalu`,
d.`stankini_lama` AS `stanskrg`,
0 AS `stanangkat`,
d.`pakai_lama` AS `pakai`,
d.`biayapemakaian_lama` AS `biayapemakaian`,
d.`administrasi_lama` AS `administrasi`,
d.`pemeliharaan_lama` AS `pemeliharaan`,
d.`retribusi_lama` AS `retribusi`,
0 AS `pelayanan`,
0 AS `airlimbah`,
0 AS `dendapakai0`,
0 AS `administrasilain`,
0 AS `pemeliharaanlain`,
0 AS `retribusilain`,
0 AS `ppn`,
d.`meterai_lama` AS `meterai`,
d.`rekair_lama` AS `rekair`,
0 AS `denda`,
d.`rekair_lama` AS `total`,
0 AS `flaghanyaabonemen`,
d.`stanlalu_baru` AS `stanlalu_usulan`,
d.`stankini_baru` AS `stanskrg_usulan`,
0 AS `stanangkat_usulan`,
d.`pakai_baru` AS `pakai_usulan`,
d.`biayapemakaian_baru` AS `biayapemakaian_usulan`,
d.`administrasi_baru` AS `administrasi_usulan`,
d.`pemeliharaan_baru` AS `pemeliharaan_usulan`,
d.`retribusi_baru` AS `retribusi_usulan`,
0 AS `pelayanan_usulan`,
0 AS `airlimbah_usulan`,
0 AS `dendapakai0_usulan`,
0 AS `administrasilain_usulan`,
0 AS `pemeliharaanlain_usulan`,
0 AS `retribusilain_usulan`,
d.`meterai_baru` AS `meterai_usulan`,
0 AS `ppn_usulan`,
d.`rekair_baru` AS `rekair_usulan`,
0 AS `denda_usulan`,
d.`rekair_baru` AS `total_usulan`,
d.`stanlalu_baru` AS `stanlalu_baru`,
d.`stankini_baru` AS `stanskrg_baru`,
0 AS `stanangkat_baru`,
d.`pakai_baru` AS `pakai_baru`,
d.`biayapemakaian_baru` AS `biayapemakaian_baru`,
d.`administrasi_baru` AS `administrasi_baru`,
d.`pemeliharaan_baru` AS `pemeliharaan_baru`,
d.`rekair_baru` AS `retribusi_baru`,
0 AS `pelayanan_baru`,
0 AS `airlimbah_baru`,
0 AS `dendapakai0_baru`,
0 AS `administrasilain_baru`,
0 AS `pemeliharaanlain_baru`,
0 AS `retribusilain_baru`,
d.`meterai_baru` AS `meterai_baru`,
0 AS `ppn_baru`,
d.`rekair_baru` AS `rekair_baru`,
0 AS `denda_baru`,
d.`rekair_baru` AS `total_baru`,
'(Selesai) Sudah Verifikasi Pusat' AS `statuspermohonan`,
0 AS `flaghapus`,
p.`tanggalba` AS `waktuupdate`
FROM `ba_usulan_koreksi_rekening` p
JOIN `ba_usulan_koreksi_rekening_periode` d ON d.`nomorba`=p.`nomorba`
JOIN `kotaparepare_dataawal`.`tampung_permohonan_pelanggan_air` pp ON pp.nomorpermohonan=p.`nomorpermohonan` AND pp.`idtipepermohonan`=@idtipepermohonan AND pp.`idpdam`=@idpdam
JOIN `kotaparepare_dataawal`.`tampung_master_pelanggan_air` pl ON pl.nosamb=d.`nosamb` AND pl.`idpdam`=@idpdam
JOIN `kotaparepare_dataawal`.`master_periode` pr ON pr.`kodeperiode`=d.`periode`
,(SELECT @id:=@lastid) AS id
WHERE p.`flaghapus`=0